const bcrypt = require("bcrypt");

const data = {
  users: [
    {
      name: "ADMIN",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "Nhat Le",
      email: "lmnhat@gmail.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Banner 1",
      slug: "nike-banner-1",
      category: "Running",
      image: "images/banner1.jpg",
      isFeatured: true,
      featuredImage: "images/banner1.jpg",
      price: 0,
      brand: "Nike",
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description: "Banner",
    },
    {
      name: "Nike Banner 2",
      slug: "nike-banner-2",
      category: "Sneakers",
      image: "images/banner1.png",
      isFeatured: true,
      featuredImage: "images/banner1.png",
      price: 0,
      brand: "Addidas",
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description: "Banner",
    },
    {
      name: "Nike Air Max",
      slug: "Sneakers",
      category: "Running",
      image: "/images/nike-air-max.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      description: "Nike shoes",
    },
    {
      name: "Nike Jordan Mid",
      slug: "nike-jordan",
      category: "Sneakers",
      image: "/images/nike-jordan-mid.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Nike shoes",
    },
    {
      name: "Nike Running",
      slug: "Running",
      category: "Running",
      image: "/images/nike-running-1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Nike shoes",
    },
    {
      name: "Nike Air OG",
      slug: "nike-basketball-1",
      category: "Basketball",
      image: "/images/nike-basketball-1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Nike shoes",
    },
    {
      name: "Nike Retro 4",
      slug: "nike-retro-4",
      category: "Running",
      image: "/images/nike-retro-4.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Nike shoes",
    },
    {
      name: "Nike Jump Man",
      slug: "nike-jump-man",
      category: "Sneakers",
      image: "/images/nike-jump-man.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Nike shoes",
    },
    {
      name: "Addidas Yeezy",
      slug: "addidas-yeezy",
      category: "Sneakers",
      image: "/images/addidas-yeezy.jpg",
      price: 70,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Addidas shoes",
    },
    {
      name: "Addidas Running",
      slug: "addidas-running",
      category: "Running",
      image: "/images/addidas-running.jpg",
      price: 70,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Addidas shoes",
    },
    {
      name: "Addidas Ultraboost",
      slug: "addidas-ultraboost",
      category: "Running",
      image: "/images/addidas-ultraboost.jpg",
      price: 70,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Addidas shoes",
    },
    {
      name: "Addidas NMD",
      slug: "addidas-nmd",
      category: "Sneakers",
      image: "/images/addidas-nmd.jpg",
      price: 70,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      description: "Addidas shoes",
    },
  ],
};

export default data;
