const data = {
  products: [
    {
      name: "Nike Air Max",
      slug: "nike-air-max",
      category: "Running Shoes",
      image: "/images/nike-air-max.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Nike shoes",
    },
    {
      name: "Nike Jordan Mid",
      slug: "nike-air-jordan",
      category: "Air Jordan",
      image: "/images/nike-jordan-mid.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Nike shoes",
    },
    {
      name: "Nike Running",
      slug: "nike-running-1",
      category: "Running",
      image: "/images/nike-running-1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Nike shoes",
    },
    {
      name: "Nike Air OG",
      slug: "nike-basketball-1",
      category: "Running",
      image: "/images/nike-basketball-1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Nike shoes",
    },
    {
      name: "Nike Retro 4",
      slug: "nike-retro-4",
      category: "Running",
      image: "/images/nike-retro-4.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Nike shoes",
    },
  ],
};

export default data;
