const data = {
  products: [
    {
      name: "Nike Air Max",
      slug: "nike-air-max",
      category: "Running Shoes",
      image: "/images/nike-air-max.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "",
    },
    {
      name: "Nike Jordan Mid",
      slug: "nike-air-jordan",
      category: "Air Jordan",
      image: "/images/nike-jordan-mid.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "",
    },
    {
      name: "Nike Jordan OG",
      slug: "nike-jordan-og",
      category: "Running",
      image: "/images/nike-jordan-og.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "",
    },
    {
      name: "Nike Air OG",
      slug: "nike-air-og",
      category: "Running",
      image: "/images/nike-air-og.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "",
    },
    {
      name: "Nike Turbo",
      slug: "nike-turbo",
      category: "Running",
      image: "/images/nike-turbo.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "",
    },
  ],
};

export default data;
